### ISSUE TITLE
invalid request 

### ISSUE THREAD

**Issue by scffs** [VimeWorld/api-docs#19]
Favicon'ка не скачивается (404)

![изображение](https://user-images.githubusercontent.com/67464545/226171476-89e486ac-77d3-4265-842a-f6bc411cd5e2.png)

Путь точно правильный указан?

**Comment by xtrafrancyz** [comment]
Если бы вы посмотрели хотя бы код страницы, то увидели бы, что фавиконки тут даже не существует.
